import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Leventis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/assets/favicon.ico" sizes="any" />;
      </Head>
      <body className={inter.className}>
      <div className="flex flex-col">
      <div className="sticky top-0 z-50">
        <Navbar />
      </div>
      {children}
    </div>    
        </body>
    </html>
  );
}
